name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        lfs: true
    - name: Deploying dev version 
      run: |
        sudo apt install -y build-essential
        sudo apt install -y python3 python3-pip python3-setuptools
        sudo apt install -y libsm6 libxext6 libxrender-dev
        pip3 install wheel pybind11
        pip3 install -U setuptools
        pip3 install -r requirements.txt

  test:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Testing 
      run: |
        python3 production/test/test.py
